version: '3'

services: 
    bot:
        container_name: taxibot_bot
        build:
            context: .
        depends_on: 
            - postgres
        restart: on-failure
        networks: 
            - taxibot_net
        volumes: 
            - ./:/taxibot

    postgres:
        container_name: taxibot_db
        image: postgres:12-alpine
        restart: on-failure
        ports:
            - 5432:5432
        env_file:
            - .env
        networks: 
            - taxibot_net
        volumes: 
            - postgres-data:/var/lib/postgresql/data

networks: 
    taxibot_net:
        driver: bridge

volumes:
    postgres-data: